### ISSUE TITLE
Uninformative/messy predict output for mlr3 LearnerRegr

### ISSUE THREAD

**Issue by dandls** [giuseppec/iml#213]
Problem: 
Unfortunately, the column name of the output of the default `predict`-function for `mlr3` `LearnerRegr` is rather messy. 

Example: 
```
> library("mlr3")
> library("rpart")
> library("iml")
> 
> task = tsk("mtcars")
> task$target_names
[1] "mpg"
> 
> mod = lrn("regr.rpart")$train(task)
> 
> pred = Predictor$new(mod, data = task$data(), y = "mpg")
> head(pred$predict(task$data()))
  predict.model..newdata...newdata.
1                          18.26429
2                          18.26429
3                          26.66364
4                          18.26429
5                          18.26429
6                          18.26429
```
Solution: 
[This line of code](https://github.com/giuseppec/iml/blob/a52c80748b9a2a4881431281f857ef4b314cbe84/R/create_predict_fun.R#L45) should be replaced, e.g., by  `data.frame(pred = predict(model, newdata = newdata))`.

**Comment by mb706** [comment]
maybe call it 'response' to be consistent with mlr3?
